### PR TITLE
Support Magisk 20

### PR DESCRIPTION
**Pull request by cruizh**

### CODE REVIEW

**Comment by xerta555** [comment]
Your commit isn't complete to make the module works again at 100%, i'm actually working on the next BETA.

**Comment by cruizh** [comment]
This seems to work just fine for me, although I am not familiar enough with the details so I may be missing something.

**Comment by xerta555** [comment]
> This seems to work just fine for me, although I am not familiar enough with the details so I may be missing something.

It works for you bcz u don't have uninstall and install again the module.

**Comment by xerta555** [comment]
Compatibility added.

**Pull request closed without merging**
